// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_grownt_desafio/test/features/character_listing/data/datasource/character_listing_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_grownt_desafio/src/core/data/local/local_storage_manager.dart'
    as _i5;
import 'package:flutter_grownt_desafio/src/core/data/remote/http_manager.dart'
    as _i3;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpManager extends _i1.Mock implements _i3.HttpManager {
  @override
  _i4.Future<_i2.Response<dynamic>> restRequest({
    required String? url,
    required String? method,
    Map<dynamic, dynamic>? headers,
    Map<dynamic, dynamic>? body = const {},
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restRequest, [], {
              #url: url,
              #method: method,
              #headers: headers,
              #body: body,
              #parameters: parameters,
            }),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(#restRequest, [], {
                  #url: url,
                  #method: method,
                  #headers: headers,
                  #body: body,
                  #parameters: parameters,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(#restRequest, [], {
                  #url: url,
                  #method: method,
                  #headers: headers,
                  #body: body,
                  #parameters: parameters,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [ILocalStorageCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalStorageCaller extends _i1.Mock
    implements _i5.ILocalStorageCaller {
  @override
  _i4.Future<_i6.Either<Error, bool>> saveData({
    required String? table,
    required String? key,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [], {
              #table: table,
              #key: key,
              #value: value,
            }),
            returnValue: _i4.Future<_i6.Either<Error, bool>>.value(
              _i7.dummyValue<_i6.Either<Error, bool>>(
                this,
                Invocation.method(#saveData, [], {
                  #table: table,
                  #key: key,
                  #value: value,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<Error, bool>>.value(
                  _i7.dummyValue<_i6.Either<Error, bool>>(
                    this,
                    Invocation.method(#saveData, [], {
                      #table: table,
                      #key: key,
                      #value: value,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<Error, bool>>);

  @override
  _i4.Future<_i6.Either<dynamic, dynamic>> restoreData({
    required String? table,
    required String? key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreData, [], {#table: table, #key: key}),
            returnValue: _i4.Future<_i6.Either<dynamic, dynamic>>.value(
              _i7.dummyValue<_i6.Either<dynamic, dynamic>>(
                this,
                Invocation.method(#restoreData, [], {#table: table, #key: key}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<dynamic, dynamic>>.value(
                  _i7.dummyValue<_i6.Either<dynamic, dynamic>>(
                    this,
                    Invocation.method(#restoreData, [], {
                      #table: table,
                      #key: key,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<dynamic, dynamic>>);

  @override
  _i4.Future<_i6.Either<String, bool>> deleteKey({
    required String? table,
    required String? key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKey, [], {#table: table, #key: key}),
            returnValue: _i4.Future<_i6.Either<String, bool>>.value(
              _i7.dummyValue<_i6.Either<String, bool>>(
                this,
                Invocation.method(#deleteKey, [], {#table: table, #key: key}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<String, bool>>.value(
                  _i7.dummyValue<_i6.Either<String, bool>>(
                    this,
                    Invocation.method(#deleteKey, [], {
                      #table: table,
                      #key: key,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<Error, List<String>>> getAllKeys(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#getAllKeys, [table]),
            returnValue: _i4.Future<_i6.Either<Error, List<String>>>.value(
              _i7.dummyValue<_i6.Either<Error, List<String>>>(
                this,
                Invocation.method(#getAllKeys, [table]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<Error, List<String>>>.value(
                  _i7.dummyValue<_i6.Either<Error, List<String>>>(
                    this,
                    Invocation.method(#getAllKeys, [table]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<Error, List<String>>>);

  @override
  _i4.Future<_i6.Either<Error, List<dynamic>>> getAllValues(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#getAllValues, [table]),
            returnValue: _i4.Future<_i6.Either<Error, List<dynamic>>>.value(
              _i7.dummyValue<_i6.Either<Error, List<dynamic>>>(
                this,
                Invocation.method(#getAllValues, [table]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<Error, List<dynamic>>>.value(
                  _i7.dummyValue<_i6.Either<Error, List<dynamic>>>(
                    this,
                    Invocation.method(#getAllValues, [table]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<Error, List<dynamic>>>);

  @override
  _i4.Future<_i6.Either<Error, Map<dynamic, dynamic>>> getAllEntries(
    String? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllEntries, [table]),
            returnValue:
                _i4.Future<_i6.Either<Error, Map<dynamic, dynamic>>>.value(
                  _i7.dummyValue<_i6.Either<Error, Map<dynamic, dynamic>>>(
                    this,
                    Invocation.method(#getAllEntries, [table]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<Error, Map<dynamic, dynamic>>>.value(
                  _i7.dummyValue<_i6.Either<Error, Map<dynamic, dynamic>>>(
                    this,
                    Invocation.method(#getAllEntries, [table]),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<Error, Map<dynamic, dynamic>>>);

  @override
  _i4.Future<_i6.Either<Error, bool>> clearAll({required String? table}) =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, [], {#table: table}),
            returnValue: _i4.Future<_i6.Either<Error, bool>>.value(
              _i7.dummyValue<_i6.Either<Error, bool>>(
                this,
                Invocation.method(#clearAll, [], {#table: table}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i6.Either<Error, bool>>.value(
                  _i7.dummyValue<_i6.Either<Error, bool>>(
                    this,
                    Invocation.method(#clearAll, [], {#table: table}),
                  ),
                ),
          )
          as _i4.Future<_i6.Either<Error, bool>>);
}
