// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_grownt_desafio/test/features/character_listing/presentation/screens/character_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_grownt_desafio/src/core/error/failure.dart' as _i5;
import 'package:flutter_grownt_desafio/src/features/character_listing/domain/entities/character_filters.dart'
    as _i7;
import 'package:flutter_grownt_desafio/src/features/character_listing/domain/entities/character_listing.dart'
    as _i6;
import 'package:flutter_grownt_desafio/src/features/character_listing/domain/repositories/i_character_listing_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ICharacterListingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICharacterListingRepository extends _i1.Mock
    implements _i2.ICharacterListingRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>> getCharacters(
    _i7.CharacterFilters? filters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacters, [filters]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CharacterListing>>(
                    this,
                    Invocation.method(#getCharacters, [filters]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CharacterListing>>(
                    this,
                    Invocation.method(#getCharacters, [filters]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<int>>> toggleCharacterFavoriteStatus(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCharacterFavoriteStatus, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, List<int>>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, List<int>>>(
                this,
                Invocation.method(#toggleCharacterFavoriteStatus, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<int>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, List<int>>>(
                    this,
                    Invocation.method(#toggleCharacterFavoriteStatus, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<int>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<int>>> getFavoriteCharacterIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteCharacterIds, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, List<int>>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, List<int>>>(
                this,
                Invocation.method(#getFavoriteCharacterIds, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<int>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, List<int>>>(
                    this,
                    Invocation.method(#getFavoriteCharacterIds, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<int>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>
  getFavoriteCharacters() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteCharacters, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CharacterListing>>(
                    this,
                    Invocation.method(#getFavoriteCharacters, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CharacterListing>>(
                    this,
                    Invocation.method(#getFavoriteCharacters, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.CharacterListing>>);
}
